// Generated by gencpp from file pcd_reader/read_pcdRequest.msg
// DO NOT EDIT!


#ifndef PCD_READER_MESSAGE_READ_PCDREQUEST_H
#define PCD_READER_MESSAGE_READ_PCDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcd_reader
{
template <class ContainerAllocator>
struct read_pcdRequest_
{
  typedef read_pcdRequest_<ContainerAllocator> Type;

  read_pcdRequest_()
    : file_name()  {
    }
  read_pcdRequest_(const ContainerAllocator& _alloc)
    : file_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::pcd_reader::read_pcdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcd_reader::read_pcdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct read_pcdRequest_

typedef ::pcd_reader::read_pcdRequest_<std::allocator<void> > read_pcdRequest;

typedef boost::shared_ptr< ::pcd_reader::read_pcdRequest > read_pcdRequestPtr;
typedef boost::shared_ptr< ::pcd_reader::read_pcdRequest const> read_pcdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcd_reader::read_pcdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pcd_reader

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcd_reader::read_pcdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcd_reader::read_pcdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcd_reader::read_pcdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2415261c9605b9f38867ffbbe495fc04";
  }

  static const char* value(const ::pcd_reader::read_pcdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2415261c9605b9f3ULL;
  static const uint64_t static_value2 = 0x8867ffbbe495fc04ULL;
};

template<class ContainerAllocator>
struct DataType< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcd_reader/read_pcdRequest";
  }

  static const char* value(const ::pcd_reader::read_pcdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_name\n\
";
  }

  static const char* value(const ::pcd_reader::read_pcdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct read_pcdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcd_reader::read_pcdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcd_reader::read_pcdRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCD_READER_MESSAGE_READ_PCDREQUEST_H
