// Generated by gencpp from file region_growing/region_growRequest.msg
// DO NOT EDIT!


#ifndef REGION_GROWING_MESSAGE_REGION_GROWREQUEST_H
#define REGION_GROWING_MESSAGE_REGION_GROWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace region_growing
{
template <class ContainerAllocator>
struct region_growRequest_
{
  typedef region_growRequest_<ContainerAllocator> Type;

  region_growRequest_()
    {
    }
  region_growRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::region_growing::region_growRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::region_growing::region_growRequest_<ContainerAllocator> const> ConstPtr;

}; // struct region_growRequest_

typedef ::region_growing::region_growRequest_<std::allocator<void> > region_growRequest;

typedef boost::shared_ptr< ::region_growing::region_growRequest > region_growRequestPtr;
typedef boost::shared_ptr< ::region_growing::region_growRequest const> region_growRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::region_growing::region_growRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::region_growing::region_growRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace region_growing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::region_growing::region_growRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::region_growing::region_growRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::region_growing::region_growRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::region_growing::region_growRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::region_growing::region_growRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::region_growing::region_growRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::region_growing::region_growRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::region_growing::region_growRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::region_growing::region_growRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "region_growing/region_growRequest";
  }

  static const char* value(const ::region_growing::region_growRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::region_growing::region_growRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::region_growing::region_growRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::region_growing::region_growRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct region_growRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::region_growing::region_growRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::region_growing::region_growRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REGION_GROWING_MESSAGE_REGION_GROWREQUEST_H
