// Generated by gencpp from file region_growing/region_grow.msg
// DO NOT EDIT!


#ifndef REGION_GROWING_MESSAGE_REGION_GROW_H
#define REGION_GROWING_MESSAGE_REGION_GROW_H

#include <ros/service_traits.h>


#include <region_growing/region_growRequest.h>
#include <region_growing/region_growResponse.h>


namespace region_growing
{

struct region_grow
{

typedef region_growRequest Request;
typedef region_growResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct region_grow
} // namespace region_growing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::region_growing::region_grow > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::region_growing::region_grow&) { return value(); }
};

template<>
struct DataType< ::region_growing::region_grow > {
  static const char* value()
  {
    return "region_growing/region_grow";
  }

  static const char* value(const ::region_growing::region_grow&) { return value(); }
};


// service_traits::MD5Sum< ::region_growing::region_growRequest> should match 
// service_traits::MD5Sum< ::region_growing::region_grow > 
template<>
struct MD5Sum< ::region_growing::region_growRequest>
{
  static const char* value()
  {
    return MD5Sum< ::region_growing::region_grow >::value();
  }
  static const char* value(const ::region_growing::region_growRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::region_growing::region_growRequest> should match 
// service_traits::DataType< ::region_growing::region_grow > 
template<>
struct DataType< ::region_growing::region_growRequest>
{
  static const char* value()
  {
    return DataType< ::region_growing::region_grow >::value();
  }
  static const char* value(const ::region_growing::region_growRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::region_growing::region_growResponse> should match 
// service_traits::MD5Sum< ::region_growing::region_grow > 
template<>
struct MD5Sum< ::region_growing::region_growResponse>
{
  static const char* value()
  {
    return MD5Sum< ::region_growing::region_grow >::value();
  }
  static const char* value(const ::region_growing::region_growResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::region_growing::region_growResponse> should match 
// service_traits::DataType< ::region_growing::region_grow > 
template<>
struct DataType< ::region_growing::region_growResponse>
{
  static const char* value()
  {
    return DataType< ::region_growing::region_grow >::value();
  }
  static const char* value(const ::region_growing::region_growResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REGION_GROWING_MESSAGE_REGION_GROW_H
