// Generated by gencpp from file car_body_defect_detect/read_pcd.msg
// DO NOT EDIT!


#ifndef CAR_BODY_DEFECT_DETECT_MESSAGE_READ_PCD_H
#define CAR_BODY_DEFECT_DETECT_MESSAGE_READ_PCD_H

#include <ros/service_traits.h>


#include <car_body_defect_detect/read_pcdRequest.h>
#include <car_body_defect_detect/read_pcdResponse.h>


namespace car_body_defect_detect
{

struct read_pcd
{

typedef read_pcdRequest Request;
typedef read_pcdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct read_pcd
} // namespace car_body_defect_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_body_defect_detect::read_pcd > {
  static const char* value()
  {
    return "2415261c9605b9f38867ffbbe495fc04";
  }

  static const char* value(const ::car_body_defect_detect::read_pcd&) { return value(); }
};

template<>
struct DataType< ::car_body_defect_detect::read_pcd > {
  static const char* value()
  {
    return "car_body_defect_detect/read_pcd";
  }

  static const char* value(const ::car_body_defect_detect::read_pcd&) { return value(); }
};


// service_traits::MD5Sum< ::car_body_defect_detect::read_pcdRequest> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::read_pcd > 
template<>
struct MD5Sum< ::car_body_defect_detect::read_pcdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::read_pcd >::value();
  }
  static const char* value(const ::car_body_defect_detect::read_pcdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::read_pcdRequest> should match 
// service_traits::DataType< ::car_body_defect_detect::read_pcd > 
template<>
struct DataType< ::car_body_defect_detect::read_pcdRequest>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::read_pcd >::value();
  }
  static const char* value(const ::car_body_defect_detect::read_pcdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_body_defect_detect::read_pcdResponse> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::read_pcd > 
template<>
struct MD5Sum< ::car_body_defect_detect::read_pcdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::read_pcd >::value();
  }
  static const char* value(const ::car_body_defect_detect::read_pcdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::read_pcdResponse> should match 
// service_traits::DataType< ::car_body_defect_detect::read_pcd > 
template<>
struct DataType< ::car_body_defect_detect::read_pcdResponse>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::read_pcd >::value();
  }
  static const char* value(const ::car_body_defect_detect::read_pcdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_BODY_DEFECT_DETECT_MESSAGE_READ_PCD_H
