// Generated by gencpp from file car_body_defect_detect/view_pointcloud.msg
// DO NOT EDIT!


#ifndef CAR_BODY_DEFECT_DETECT_MESSAGE_VIEW_POINTCLOUD_H
#define CAR_BODY_DEFECT_DETECT_MESSAGE_VIEW_POINTCLOUD_H

#include <ros/service_traits.h>


#include <car_body_defect_detect/view_pointcloudRequest.h>
#include <car_body_defect_detect/view_pointcloudResponse.h>


namespace car_body_defect_detect
{

struct view_pointcloud
{

typedef view_pointcloudRequest Request;
typedef view_pointcloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct view_pointcloud
} // namespace car_body_defect_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_body_defect_detect::view_pointcloud > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::car_body_defect_detect::view_pointcloud&) { return value(); }
};

template<>
struct DataType< ::car_body_defect_detect::view_pointcloud > {
  static const char* value()
  {
    return "car_body_defect_detect/view_pointcloud";
  }

  static const char* value(const ::car_body_defect_detect::view_pointcloud&) { return value(); }
};


// service_traits::MD5Sum< ::car_body_defect_detect::view_pointcloudRequest> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::view_pointcloud > 
template<>
struct MD5Sum< ::car_body_defect_detect::view_pointcloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::view_pointcloud >::value();
  }
  static const char* value(const ::car_body_defect_detect::view_pointcloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::view_pointcloudRequest> should match 
// service_traits::DataType< ::car_body_defect_detect::view_pointcloud > 
template<>
struct DataType< ::car_body_defect_detect::view_pointcloudRequest>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::view_pointcloud >::value();
  }
  static const char* value(const ::car_body_defect_detect::view_pointcloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_body_defect_detect::view_pointcloudResponse> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::view_pointcloud > 
template<>
struct MD5Sum< ::car_body_defect_detect::view_pointcloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::view_pointcloud >::value();
  }
  static const char* value(const ::car_body_defect_detect::view_pointcloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::view_pointcloudResponse> should match 
// service_traits::DataType< ::car_body_defect_detect::view_pointcloud > 
template<>
struct DataType< ::car_body_defect_detect::view_pointcloudResponse>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::view_pointcloud >::value();
  }
  static const char* value(const ::car_body_defect_detect::view_pointcloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_BODY_DEFECT_DETECT_MESSAGE_VIEW_POINTCLOUD_H
