// Generated by gencpp from file car_body_defect_detect/visualize_input.msg
// DO NOT EDIT!


#ifndef CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_INPUT_H
#define CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_INPUT_H

#include <ros/service_traits.h>


#include <car_body_defect_detect/visualize_inputRequest.h>
#include <car_body_defect_detect/visualize_inputResponse.h>


namespace car_body_defect_detect
{

struct visualize_input
{

typedef visualize_inputRequest Request;
typedef visualize_inputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize_input
} // namespace car_body_defect_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_body_defect_detect::visualize_input > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::car_body_defect_detect::visualize_input&) { return value(); }
};

template<>
struct DataType< ::car_body_defect_detect::visualize_input > {
  static const char* value()
  {
    return "car_body_defect_detect/visualize_input";
  }

  static const char* value(const ::car_body_defect_detect::visualize_input&) { return value(); }
};


// service_traits::MD5Sum< ::car_body_defect_detect::visualize_inputRequest> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_input > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_inputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_input >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_inputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_inputRequest> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_input > 
template<>
struct DataType< ::car_body_defect_detect::visualize_inputRequest>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_input >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_inputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_body_defect_detect::visualize_inputResponse> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_input > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_inputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_input >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_inputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_inputResponse> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_input > 
template<>
struct DataType< ::car_body_defect_detect::visualize_inputResponse>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_input >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_inputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_INPUT_H
