// Generated by gencpp from file car_body_defect_detect/visualize_region_grow.msg
// DO NOT EDIT!


#ifndef CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_REGION_GROW_H
#define CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_REGION_GROW_H

#include <ros/service_traits.h>


#include <car_body_defect_detect/visualize_region_growRequest.h>
#include <car_body_defect_detect/visualize_region_growResponse.h>


namespace car_body_defect_detect
{

struct visualize_region_grow
{

typedef visualize_region_growRequest Request;
typedef visualize_region_growResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize_region_grow
} // namespace car_body_defect_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_body_defect_detect::visualize_region_grow > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::car_body_defect_detect::visualize_region_grow&) { return value(); }
};

template<>
struct DataType< ::car_body_defect_detect::visualize_region_grow > {
  static const char* value()
  {
    return "car_body_defect_detect/visualize_region_grow";
  }

  static const char* value(const ::car_body_defect_detect::visualize_region_grow&) { return value(); }
};


// service_traits::MD5Sum< ::car_body_defect_detect::visualize_region_growRequest> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_region_grow > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_region_growRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_region_grow >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_region_growRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_region_growRequest> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_region_grow > 
template<>
struct DataType< ::car_body_defect_detect::visualize_region_growRequest>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_region_grow >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_region_growRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_body_defect_detect::visualize_region_growResponse> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_region_grow > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_region_growResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_region_grow >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_region_growResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_region_growResponse> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_region_grow > 
template<>
struct DataType< ::car_body_defect_detect::visualize_region_growResponse>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_region_grow >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_region_growResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_REGION_GROW_H
