// Generated by gencpp from file car_body_defect_detect/visualize_area.msg
// DO NOT EDIT!


#ifndef CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_AREA_H
#define CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_AREA_H

#include <ros/service_traits.h>


#include <car_body_defect_detect/visualize_areaRequest.h>
#include <car_body_defect_detect/visualize_areaResponse.h>


namespace car_body_defect_detect
{

struct visualize_area
{

typedef visualize_areaRequest Request;
typedef visualize_areaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize_area
} // namespace car_body_defect_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_body_defect_detect::visualize_area > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::car_body_defect_detect::visualize_area&) { return value(); }
};

template<>
struct DataType< ::car_body_defect_detect::visualize_area > {
  static const char* value()
  {
    return "car_body_defect_detect/visualize_area";
  }

  static const char* value(const ::car_body_defect_detect::visualize_area&) { return value(); }
};


// service_traits::MD5Sum< ::car_body_defect_detect::visualize_areaRequest> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_area > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_areaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_area >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_areaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_areaRequest> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_area > 
template<>
struct DataType< ::car_body_defect_detect::visualize_areaRequest>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_area >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_areaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_body_defect_detect::visualize_areaResponse> should match 
// service_traits::MD5Sum< ::car_body_defect_detect::visualize_area > 
template<>
struct MD5Sum< ::car_body_defect_detect::visualize_areaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_body_defect_detect::visualize_area >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_areaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_body_defect_detect::visualize_areaResponse> should match 
// service_traits::DataType< ::car_body_defect_detect::visualize_area > 
template<>
struct DataType< ::car_body_defect_detect::visualize_areaResponse>
{
  static const char* value()
  {
    return DataType< ::car_body_defect_detect::visualize_area >::value();
  }
  static const char* value(const ::car_body_defect_detect::visualize_areaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_BODY_DEFECT_DETECT_MESSAGE_VISUALIZE_AREA_H
